version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - .:/app

  backend:
    build:
      context: ./ML
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./ML:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
